name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: |
          npm ci
          npm run tar

      - name: Run Tests
        run: |
          cd test && npx cds deploy -2 sqlite:db/testservice.db && cd ..
          npm run test

      - name: get-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Parse changelog
        id: parse-changelog
        uses: schwma/parse-changelog-action@v1.2.0
        with:
          version: "${{ steps.package-version.outputs.current-version }}"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.package-version.outputs.current-version }}"
          body: "${{ steps.parse-changelog.outputs.body }}"

      - name: Publish to npm
        run: |
          cd gen
          npm publish cap-js-data-inspector-*.tgz --access public --provenance --dry-run
